### ISSUE TITLE
Reroute error

### ISSUE THREAD

**Issue by Atreia5710** [Smirnov75/ComfyUI-mxToolkit#18]
Reroute doesn't work after update ComfyUI to v0.2.2.
I have an error in browser console:
```
app.ts:2980 TypeError: this.addInput is not a function
    at new MxRerouteNode (Reroute.js:13:10)
    at Object.createNode (litegraph.es.js:386:19)
    at ComfyApp.addNodeOnGraph (app.ts:2980:28)
    at addNode (NodeSearchBoxPopover.vue:76:20)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at emit (runtime-core.esm-bundler.js:726:5)
    at createVNode.onOptionSelect._cache.<computed>._cache.<computed> (NodeSearchBox.vue:175:28)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
```

One of the way fix  it:
https://github.com/Smirnov75/ComfyUI-mxToolkit/blob/7568454b98cebbec2f2b2b5adae5710af099c03c/js/Reroute.js#L8-L9
change to:
```
	class MxRerouteNode extends LGraphNode {
		constructor(title = MxRerouteNode.title) {
			super(title);
```
